name: Check security vulnerabilities

on: [push, pull_request]

jobs:
  security-advisories:
    name: SecurityAdvisories
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SecurityAdvisories
      uses: docker://gregurco/security-advisories-ga
